name: task_manager_app
description: A task management app with Firebase integration for real-time synchronization.

# The following line prevents the package from being accidentally published to pub.dev
publish_to: 'none'

# Version of your app
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core package for initializing Firebase
  firebase_core: ^3.0.0

  # Firebase Authentication for user sign-in and sign-up
  firebase_auth: ^5.3.2

  # Cloud Firestore for real-time database
  cloud_firestore: ^5.0.0

  # Provider for state management
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Flutter lints for linting rules
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # Add any assets here if needed
    # - assets/
    # Example of including fonts:
    # fonts:
    #   - family: Roboto
    #     fonts:
    #       - asset: fonts/Roboto-Regular.ttf
    #       - asset: fonts/Roboto-Bold.ttf
